services:
  - type: web
    name: lashir-api
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./sanne/Dockerfile
    envVars:
      - key: FLAT_IO_API_KEY
        value: your_flat_io_api_key_here
      - key: PORT
        value: 10000
