services:
  - type: web
    name: lashir-api
    plan: free
    dockerfilePath: ./go-api/Dockerfile
    port: 8080  # Explicit port declaration
    envVars:
      - key: PYTHON_AUDIO_URL
        value: https://lashir-audio.onrender.com
      - key: PYTHON_MUSIC21_URL
        value: https://lashir-music21.onrender.com

  - type: web
    name: lashir-audio
    plan: free
    dockerfilePath: ./python-audio/Dockerfile
    port: 5000  # Must match your Python service port

  - type: web
    name: lashir-music21
    plan: free
    dockerfilePath: ./python-music21/Dockerfile
    port: 5001  # Must match your Music21 service port
