name: Docker Compose Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Docker Compose
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # Build and test services
      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build
          docker compose ps  # Verify services are running
          
          # Optional: Add test commands (e.g., curl endpoints)
          docker compose run go-api sh -c "curl -s http://python-audio:5000/detect"
